bio/urls.py
__author__ = 'alexaled'

from django.conf.urls.defaults import patterns, url

import views

urlpatterns = patterns('',
                       url(r'^get-bio/$',                views.my_bio_view,
                                                            name='get-bio'),
                       url(r'^edit-bio/(\d+)/$',         views.edit_data,
                                                        name='edit_bio'),
                       url(r'^edit-bio-reverse/(\d+)/$', views.edit_data,
                                    {'rev': True}, name='edit_bio_reverse'),
                       url(r'^$',                        views.my_bio_view),
                       url(r'^context-proc/$',           views.add_conf,
                                                         name='context-proc'),
                       url(r'^req-list/$',               views.http_view,
                                                         name='req-list'),
                       url(r'^edit-request/(\d+)/$',     views.edit_data_http,
                                                         name='edit_http'),
                       )

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/',  include(admin.site.urls)),
    url(r'^my-bio/', include('bio.urls')),
    url(r'^$',       include('bio.urls')),

    #accounts
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),

)

urlpatterns += staticfiles_urlpatterns()

bio/models.py
from django.db import models
from django.db.models.signals import post_init, post_save, post_delete


def signals_init(sender, **kwargs):
    save_signal(sender, 'init')


def signals_save(sender, **kwargs):
    save_signal(sender, 'save')


def signals_delete(sender, **kwargs):
    save_signal(sender, 'delete')


def save_signal(sender, signal):
    if sender.__name__ != 'DbSignals':
        obj = DbSignals()
        obj.model = sender.__name__
        obj.signal = signal
        obj.save()

post_init.connect(signals_init, dispatch_uid='Coffee_Cups_test.bio')
post_save.connect(signals_save, dispatch_uid='Coffee_Cups_test.bio')
post_delete.connect(signals_delete, dispatch_uid='Coffee_Cups_test.bio')


class MyBio(models.Model):
    '''
    Main model for my bio
        first_name - my first name
        last_name - my last name
        birth_date = my birth date
        biography - my biography text area
        contacts - my contacts area
    '''
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField()
    biography = models.TextField(blank=True)
    contacts = models.TextField()


class HttpRequestSave(models.Model):
    '''
    HTTP request
    '''
    http_request = models.CharField(max_length=300)
    remote_addr = models.IPAddressField(blank=True)
    priority = models.IntegerField()
    datatime = models.DateTimeField(auto_now_add=True)


class DbSignals(models.Model):
    """
    table for signals saver
    """
    signal = models.CharField(max_length=50, blank=True)
    model = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(blank=True, auto_now_add=True)

bio/forms.py
__author__ = 'alexaled'

from django import forms

from models import MyBio, HttpRequestSave


class CalendarWidget(forms.TextInput):

    class Media:
        js = ('/media/js/jquery-1.5.1.min.js',
              '/media/js/jquery.datapick.js')
        css = {'all' : '/media/css/css/jquery-ui-1.8.14.custom.css'}


class BioForm(forms.ModelForm):
    birth_date = forms.DateField(widget=CalendarWidget)

    class Meta:
        model = MyBio


class HttpEditForm(forms.ModelForm):

    class Meta:
        model = HttpRequestSave

bio/views.py
__author__ = 'alexaled'

from django.shortcuts import render_to_response, RequestContext, \
    HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.utils import simplejson
import time

from models import MyBio, HttpRequestSave
from context_processors import add_conf_proc
from forms import BioForm, HttpEditForm


def my_bio_view(request):
    """
    for main page view my bio all data
    """
    all_bio = MyBio.objects.all()
    bio_dict = {}
    for bio_inst in all_bio:
        bio_inst_dict = {'id': bio_inst.id,
                         'first_name': bio_inst.first_name,
                         'last_name': bio_inst.last_name,
                         'birth_date': bio_inst.birth_date,
                         'biography': bio_inst.biography,
                         'contacts': bio_inst.contacts}
        bio_dict[bio_inst] = bio_inst_dict

    return render_to_response('bio/my_bio_view.html', {'my_bio': bio_dict})


@login_required
def edit_data(request, id=1, rev=False):
    """
    views for edit data
    """
    try:
        my_bio_edit = MyBio.objects.get(id=id)
    except:
        my_bio_edit = MyBio.objects.create()

    if request.POST:
        # 3 sec sleep for ajax submit
        if request.is_ajax():
            time.sleep(3)
        form = BioForm(request.POST, instance=my_bio_edit)
        if rev:
            form.fields.keyOrder.reverse()
        if form.is_valid():
            form.save()
            if request.is_ajax():
                json_result = simplejson.dumps({'status': "done_status"})
        else:
            if request.is_ajax():
                error_string = ''
                n = 0
                for err in form.errors:
                    n += 1
                    if n == len(form.errors):
                        error_string = error_string + " " + err + " "
                    else:
                        error_string = error_string + " " + err + ", "

                json_result = simplejson.dumps({'status': 'fail_status',
                                                'errors': error_string})
        if request.is_ajax():
            return HttpResponse(json_result, mimetype='application/javascript')
    else:
        form = BioForm(instance=my_bio_edit)
        if rev:
                form.fields.keyOrder.reverse()

    return render_to_response('bio/edit_data.html',
            {'form': form, 'id': id, 'reverse': rev, 'obj': my_bio_edit})


@login_required
def edit_data_http(request, id=1):
    """
    views for edit data
    """

    try:
        http_edit = HttpRequestSave.objects.get(id=id)
    except:
        http_edit = HttpRequestSave.objects.create()

    if request.POST:
        form = HttpEditForm(request.POST, instance=http_edit)
        if form.is_valid():
            form.save()
            return redirect('/my-bio/req-list')
    else:
        form = HttpEditForm(instance=http_edit)

    return render_to_response('bio/http_request_edit.html',
            {'form': form, 'id': id, 'obj': http_edit})


def add_conf(request):
    """
    view apps in settings for context proc
    """
    return render_to_response('bio/cont_proc.html', {},
                              context_instance=RequestContext(request,
                                            processors=[add_conf_proc]))


def http_view(request):
    """
    view http request
    """
    ten_last_req = HttpRequestSave.objects.order_by('-priority')[0:10]
    return render_to_response('bio/http_request.html',
            {'ten_last_req': ten_last_req})

templates/base.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link type="text/css" href="{{ STATIC_PREFIX }}css/style.css" rel="stylesheet" />
    <link type="text/css" href="{{ STATIC_PREFIX }}css/css/ui-lightness/jquery-ui-1.8.14.custom.css" rel="stylesheet" />
    <script type="text/javascript" src="{{ STATIC_PREFIX }}js/jquery-1.5.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_PREFIX }}js/jquery-ui-1.8.14.custom.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_PREFIX }}js/jquery.form.js"></script>

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div id="urls">
        {% block url_line %}
        {% endblock %}
    </div>
    <div id="contents">
        {% block content %}
        {% endblock %}
    </div>
    <div id="urls_main">
        {% block url_main_page %}
        {% endblock %}
    </div>
</body>
</html>

templates/bio/cont_proc.html
{% extends "base.html" %}

{% block title%}
Content proc result
{% endblock %}

{% block content %}
  <p>{{ settings.INSTALLED_APPS }}</p>
{% endblock %}

{% block url_main_page %}
        <a href={% url get-bio %}>Main page</a>
{% endblock %}

templates/bio/edit_data.html
{% extends "base.html" %}
{% load edit_link %}

{% block title %}
    Edit data
{% endblock %}

{% block url_line %}
    {% if reverse %}
        <a href={% url edit_bio id %}>Normal order fields</a>
    {% else %}
        <a href={% url edit_bio_reverse id %}>Reverse fields</a>
    {% endif %}
        <a href="{% edit_link obj%}">Edit in admin</a>
{% endblock %}

{% block content %}
    {{ form.media }}
	<script type="text/javascript">

             function submitStart(formData, jqForm, options) {
                    $("#errors").hide();
                    setEnabledDisabled(true);
                    $("#sendwrapper").prepend('<span>Sending your bio, please wait... </span>')
                    return true;
                }

             function submitSuccess(responseText, statusText, xhr, form)  {
                    json_resp_obj = $.parseJSON(responseText);
                    setEnabledDisabled("")

                    $("#errors, #sendwrapper, #done").empty();

                    if (json_resp_obj.status == "done_status") {
                         $("#done").show();
                         $("#done").prepend("<p>Data saved done.</p>")
                    } else{
                    $("#errors").show();
                    if (json_resp_obj.errors.indexOf(',') == -1) {
                         $("#errors").prepend("<p>Error in field "+ json_resp_obj.errors +"</p>");
                    } else {
                         $("#errors").prepend("<p>Errors in fields "+ json_resp_obj.errors +"</p>");
                    }
                    }
                }

             function setEnabledDisabled(status){
                  $("#sendbutton, #id_last_name, #id_first_name, #id_contacts, #id_biography, #id_biography").attr('disabled', status);
             }

             $(function() {
                $("#id_birth_date").datepicker({ dateFormat: 'yy-mm-dd' });
                $("#editform").ajaxForm({
                    beforeSubmit:  submitStart,
                    success:       submitSuccess});
                return false;
             });


    </script>

    <form id="editform" action="" method="post">{% csrf_token %}
        {{ form.as_p }}
    <div id="sendwrapper"></div>
     <p><input id="sendbutton" type=submit value="Submit"></p>
    </form>

    <div id="errors">
                {% for error in form.errors %}
                    <p>{{ error }} not valid.</p>
                {% endfor %}
    </div>

    <div id="done"></div>

{% endblock %}

{% block url_main_page %}
     <p><a href={% url get-bio %}>To main page</a></p>
{% endblock %}

templates/bio/http_request.html
{% extends "base.html" %}

{% block title%}
Http request page, first 10
{% endblock %}

{% block content %}
    <ol>
    {% for req in ten_last_req %}
        <li>Request <b>{{ req.http_request }}</b> from <b>{{ req.remote_addr }}
        </b> with priority <b>{{ req.priority }} </b> saved at <b>{{ req.datatime }}</b><a href={%url edit_http req.id %}> edit</a> </li>
    {% endfor %}
    </ol>
{% endblock %}

{% block url_main_page %}
    <p><a href={% url get-bio %}>To main page</a></p>
{% endblock %}

templates/bio/http_request_edit.html
{% extends "base.html" %}
{% load edit_link %}

{% block title %}
    Edit data
{% endblock %}

{% block url_line %}
    {% if reverse %}
        <a href={% url edit_bio id %}>Normal order fields</a>
    {% else %}
        <a href={% url edit_bio_reverse id %}>Reverse fields</a>
    {% endif %}
        <a href="{% edit_link obj%}">Edit in admin</a>

    <a href={% url req-list %}>Requests list</a>
{% endblock %}

{% block content %}
    <form action="" method="POST">{% csrf_token %}
        {{ form.as_p }}
    <p><input type=submit value="Submit"></p>
    </form>
{% endblock %}

{% block url_main_page %}
    <p><a href={% url get-bio %}>To main page</a></p>
{% endblock %}

templates/bio/my_bio_view.html
{% extends "base.html" %}

{% block title%}
My bio page
{% endblock %}

{% block url_line %}
   <a href={% url context-proc %}>Context processor page</a>
   <a href={% url req-list %}>Request list</a>
{% endblock %}

{% block content %}
    <div class="main">
      {% for bio_inst in my_bio %}
          <div class="fields">
            <p>First name: {{ bio_inst.first_name }}</p>
            <p>Last name:  {{ bio_inst.last_name }}</p>
            <p>Birth date: {{ bio_inst.birth_date }}</p>
            <p>Biography:  {{ bio_inst.biography }}</p>
            <p>Contacts:   {{ bio_inst.contacts }}</p>
          </div>
          <a href={% url edit_bio bio_inst.id %}>edit data</a>
      {% endfor %}
    </div>

{% endblock %}
